name: Run Cucumber Tests and Deploy Reports

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'zulu'



      - name: Checkout code
        uses: actions/checkout@v3


      - name: Install Dependencies
        run: mvn install


      - name: Run Cucumber Tests
        run: mvn test -Dtags="@plant" -X

      - name: Upload Cucumber Test Reports as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-reports
          path: test-output/cucumber-reports/


