name: Run Cucumber Tests and Deploy Reports

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Maven
        uses: s4u/setup-maven@v2
        with:
          maven-version: '3.8.7'

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: mvn install

      - name: Run Cucumber Tests
        run: mvn test -Dtags="@plant" -X