name: Run Cucumber Tests and Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'

      - name: Install Dependencies
        run: mvn install

      - name: Run Cucumber Tests
        run: mvn test -Dtags="@plant"

      - name: Deploy Reports to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4  # Reliable deployment action
        with:
          branch: gh-pages
          folder: ./target
          token: ${{ secrets.GITHUB_TOKEN }}