name: Run Cucumber Tests and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to whatever branch you want to trigger on
  pull_request:
    branches:
      - main  # Also run on pull request if desired

jobs:
  test:
    runs-on: ubuntu-latest  # Or any other OS if needed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # This is from GitHub Actions and works by default

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Adjust based on your Java version

      - name: Install Dependencies
        run: mvn install  # Replace with npm install or your preferred package manager

      - name: Run Cucumber Tests
        run: mvn test -Dtags="@plant"  # Adjust this command based on your tests

      - name: Deploy Reports to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4  # Reliable deployment action
        with:
          branch: gh-pages  # Deploy to the gh-pages branch
          folder: ./target   # The folder containing the generated HTML reports (adjust if needed)
          token: ${{ secrets.GITHUB_TOKEN }}  # Uses the GITHUB_TOKEN to authenticate