name: Run Cucumber Tests and Deploy Reports

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  workflow_dispatch:
    inputs:
      ref:
        description: 'Tag to run the workflow on'
        required: true
        default: 'master'
      tags:
        description: 'Cucumber tag to run tests with'
        required: false
        default: '@plant'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'

      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Verify Maven version (pre-installed on runner)
      - name: Verify Maven Version
        run: mvn -version

      # Install dependencies
      - name: Install Dependencies
        run: mvn install

      # Run Cucumber Tests
      - name: Run Cucumber Tests
        run: mvn test -Dtags="${{ github.event.inputs.tags || '@plant' }}"

      # Ensure reports directory exists
      - name: Ensure Reports Directory Exists
        run: mkdir -p test-output/cucumber-reports

      # Upload Cucumber Test Reports as Artifacts
      - name: Upload Cucumber Test Reports as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-reports
          path: test-output/cucumber-reports/