name: Run Cucumber Automation Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3


      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'


      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      

      - name: Install Dependencies
        run: mvn install


      - name: Run Cucumber Tests
        run: mvn test -Dtags="@plant"

      - name: Upload Extent and Cucumber Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            ./target/cucumber-reports.html         
            ./target/ExtentReports/*.html            
            ./test-output/html/HTMLreport.html