name: Run Cucumber Tests and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Or any OS you prefer

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # This is still allowed since it's from GitHub itself

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Install Dependencies
        run: mvn install

      - name: Run Cucumber Tests
        run: mvn test -Dtags="@plant"

      - name: Deploy Report to GitHub Pages
        run: |
          # Set up the directory for GitHub Pages
          mkdir gh-pages
          cp -R target/cucumber-reports.html gh-pages/  
          cp -R target/ExtentReports/*.html gh-pages/  
          cp -R test-output/html/HTMLreport.html gh-pages/  #
          
          # Configure Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Create gh-pages branch if it doesn't exist
          git checkout -b gh-pages || git checkout gh-pages
          git add .
          git commit -m "Deploy reports to GitHub Pages"
          git push origin gh-pages --force

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
